City-of-Helsinki/youth-membership-admin-ui

- .env
- .env.development
- .gitlab-ci.yml
- package.json
- src/App.tsx
- src/auth/fetchApiToken.ts
- src/graphql/apiUtils.ts
- src/graphql/client.ts
- src/graphql/dataProvider.ts
- src/graphql/generatedTypes.ts
- src/graphql/types.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/api/YouthApi.ts
- src/pages/youthProfiles/list/YouthList.tsx
- src/pages/youthProfiles/query/YouthProfileQueries.ts
- src/react-admin.d.ts
- yarn.lock
- Added required configurations to fetch data from backend. 
- Created simple list view for fetching profiles.
> OM - 537 & OM - 32 | Add backend

- package.json
- src/graphql/apiUtils.ts
- src/graphql/dataProvider.ts
- src/graphql/generatedTypes.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/api/YouthApi.ts
- src/pages/youthProfiles/constants/youthProfileConstants.ts
- src/pages/youthProfiles/create/CreateYouthProfile.tsx
- src/pages/youthProfiles/create/form/CreateYouthForm.module.css
- src/pages/youthProfiles/create/form/CreateYouthForm.tsx
- src/pages/youthProfiles/create/inputs/BirthDateInput.tsx
- src/pages/youthProfiles/create/inputs/RadioGroupInput.tsx
- src/pages/youthProfiles/create/inputs/TextInput.tsx
- src/pages/youthProfiles/helpers/__tests__/youthCreateFormValidator.test.ts
- src/pages/youthProfiles/helpers/youthCreateFormValidator.ts
- src/pages/youthProfiles/list/YouthList.tsx
- src/pages/youthProfiles/query/YouthProfileQueries.ts
- src/pages/youthProfiles/types/youthProfileTypes.ts
- src/routes.tsx
- yarn.lock
This PR makes possible for admins to create youth profiles. I wanted to add HDS - styles for create form, this resulted for needing few custom components & validation. For custom input components I decided to test out `makeStyles` hook that was suggested in [documentation](https://marmelab.com/react-admin/Fields.html).
> OM - 29 | Staff registration

- .env
- Dockerfile
Added authority value to `.env`. Value is taken from youth-membership-ui, after this change configs should be identical.
> OM - 555 | Login not working

- .env
- package.json
- src/auth/authenticate.ts
- src/auth/components/oidcCallback/OidcCallback.tsx
- src/graphql/apiUtils.ts
- src/index.tsx
- yarn.lock
- Added configurations to initialize Sentry
- Added Sentry error capturing to login, queries and mutations.
> OM -  439 | Configure sentry

- src/graphql/generatedTypes.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/api/YouthApi.ts
- src/pages/youthProfiles/list/YouthList.module.css
- src/pages/youthProfiles/list/YouthList.tsx
- src/pages/youthProfiles/query/YouthProfileQueries.ts
This PR contains few bug fixes.
- Search in lists will always query data from backend.
- Shows amount of search results below table.
- Added MembershipStatus to list view.
- Added missing localizations in list view.
> OM - 598 | Jässäri admin list view

- .env.development
- .gitlab-ci.yml
- package.json
The URL of the profile backend changed, I added the new one into the config. I also changed the production config for Tunnistamo/profile.
> OM-622 | Fix backend URLs

- src/graphql/generatedTypes.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/query/YouthProfileQueries.ts
- src/pages/youthProfiles/show/YouthDetails.tsx
Added the following fields to YouthDetails view:
- membership number
- membership status
- expiration date
- profile language
> OM - 561 | Missing fields in details view

- src/pages/youthProfiles/list/YouthList.tsx
- src/pages/youthProfiles/show/YouthDetails.tsx
- Search list parameters (first name & last name) are saved to url as parameters. After returning to list view from youth's detailed view via "back to search results button", parameters are added to text inputs and query will be executed.
- If error occurs while loading list, loading animation is will be hidden.
> OM - 560 & OM - 634 | Back button looses search results

- CONTRIBUTING.md
- README.md
- Added instructions for contributing.
- Added pointers for installing local profile & tunnistamo
(Basically this copy from youth-membership-ui)
> OM-528 | Update README

- src/pages/youthProfiles/form/YouthProfileForm.tsx
- src/pages/youthProfiles/helpers/youthCreateFormValidator.ts
I forgot to add phone field are required in previous PR.
Added extra check for email validation to prevent unwanted errors.
> OM-691 | Form validation

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/edit/EditYouthProfile.tsx
- src/pages/youthProfiles/form/YouthProfileForm.module.css
- src/pages/youthProfiles/form/YouthProfileForm.tsx
- src/pages/youthProfiles/form/inputs/BirthDateInput.tsx
- src/pages/youthProfiles/form/inputs/TextInput.tsx
- src/pages/youthProfiles/helpers/youthProfileMutationVariables.ts
- src/pages/youthProfiles/show/YouthDetails.tsx
Fixed few bugs:
- When editing email is now set to readOnly
- photoPermission field is correctly sent to backend
Also made little modifications that I missed before:
- Search parameters are now kept in the URL all the time 
- Added cancel button to edit form
- Fixed some styles.  When I update HDS it seems that default length of TextInput was changed which caused it to miss match with `Select` and `BirthDateInput` components
> OM-746 | Form fixes

- src/pages/youthProfiles/create/CreateYouthProfile.tsx
- src/pages/youthProfiles/edit/EditYouthProfile.tsx
User now gets message if error occurs while saving.
> OM-746 | Add missing error handling

- .gitlab-ci.yml
- src/index.tsx
Fix sentry environment pointing always to production.
> YM-192 | Fix sentry config

- .gitlab-ci.yml
- package.json
Fixed the URLs pointing at Helsinki profile in production. Also changed
the version number so that it's now OK for release candidate 1.
> YM-241 | Fix production config

- src/pages/youthProfiles/form/YouthProfileForm.tsx
- src/pages/youthProfiles/helpers/youthFormValidator.ts
Additional addresses are now also validated according to the same principles as `primaryAddress`.
> YM-81 | Validate additional addresses

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/form/YouthProfileForm.module.css
- src/pages/youthProfiles/form/YouthProfileForm.tsx
This PR completes the support for editing multiple addresses by allowing the user to set an address as primary.
> YM-87 | Allow primary address to be changed

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/form/YouthProfileForm.module.css
- src/pages/youthProfiles/form/YouthProfileForm.tsx
Also changes the layout to be more in line with the design in Abstract.
> YM-292 | Add missing translations

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/list/YouthList.module.css
- src/pages/youthProfiles/list/YouthList.tsx
- Buttons should now be aligned with textfields 
- Changed text on "Create button"
> YM-321 | Fix button alignment.

- package.json
- yarn.lock
This resolves a race condition in the react-admin library which caused
an error to be thrown in our applicaiton.
ref: https://github.com/marmelab/react-admin/pull/4990
> YM-288 | Update react-admin 3.6.1 → 3.8.4

- src/pages/youthProfiles/helpers/youthFormValidator.ts
We are only interested validating fields that are inside `fields` array, because of that I made a change that we loop through `fields` array and check that those values are present in `object`.
> YM-21 | Multiple contacts persons validation

- .github/PULL_REQUEST_TEMPLATE.md
I've added a PR template file.
This file will make it easier for the developer to provide all the relevant information in a consistent format.
No Jira ticket.
This has been tested by using Visual Studio Code's preview. The template has also been dogfooded for this PR description.
This template can be tested only after it has been merged into develop.
> Chore | Add PR template

- CHANGELOG.md
I updated the changelog for the upcoming release.
[YM-419](https://helsinkisolutionoffice.atlassian.net/browse/YM-419)
N/A
Check out the changelog file.
N/A
> YM-419 | Update changelog

- package.json
- yarn.lock
Fixes security warnings by runnind `audit fix` and manually upgrading `react-scripts` and `axios` into safe versions.
> Chore | Fix security warnings

- .github/workflows/review.yml
- .github/workflows/staging.yml
Allows usage of Tunnistamo also at review environment(s)
[DEVOPS-228](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-228)
Implemented to open-city-profile-ui, and tested also in created review env manually.
Access review env and sign in.
> KuVa Tunnistamo to use

- .github/workflows/production.yml
Revert configurations on production.
> HOTFIX | Fix production config

- .github/workflows/production.yml
Changed backend url variable name to be correct.
> HOTFIX | Fix backend variable name.

- .github/workflows/production.yml
- CHANGELOG.md
- package.json
> Release 1.3.1

- .github/workflows/production.yml
- CHANGELOG.md
- package.json
- Use production audience for Jassari API
> Release 1.3.2

- CHANGELOG.md
- src/graphql/generatedTypes.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/youthProfiles/form/YouthProfileForm.tsx
- src/pages/youthProfiles/show/YouthDetails.tsx
Change the language at home field to preferred contact language field in order to reflect the change we did to the public UI earlier.
Also makes the UI support all youth languages.
[YM-503](https://helsinkisolutionoffice.atlassian.net/browse/YM-503)
> YM-503 | Change language at home field to preferred contact language field

- .eslintrc.json
- CHANGELOG.md
- package.json
- src/auth/__tests__/authService.test.js
- src/auth/__tests__/authorizationService.test.js
- src/auth/authService.ts
- src/auth/components/login/Login.tsx
- src/graphql/apiUtils.ts
- src/pages/youthProfiles/constants/youthProfileConstants.ts
- src/pages/youthProfiles/form/YouthProfileForm.tsx
- src/pages/youthProfiles/helpers/__tests__/youthFormValidator.test.ts
- src/pages/youthProfiles/helpers/youthFormValidator.ts
- src/pages/youthProfiles/list/YouthList.tsx
- src/pages/youthProfiles/show/YouthDetails.tsx
- src/pages/youthProfiles/types/youthProfileTypes.ts
- src/routes.tsx
- tsconfig.json
- yarn.lock
Updates react-scripts to resolve high risk security warnings.
> Chore | Resolve security errors

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
Increase k8s cpu limit
DEVOPS-402 CPU Throttling high alerts
[DEVOPS-402](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-402)
> DEVOPS-402 increase k8s cpu limit to 10m

- azure-pipelines-develop.yml
- azure-pipelines-master.yml
[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
> Pipeline YML files

- .prod/nginx.conf
- Dockerfile
[DEVOPS-487](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487)
[DEVOPS-487]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Openshift write accesses

- .github/workflows/devops_review_tunnistamo.yml
- .github/workflows/review.yml
- browser-tests/pages/loginSelector.ts
- package.json
- yarn.lock
[DEVOPS-487](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487)
[DEVOPS-487]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Browser tests on Platta review

- Dockerfile
[YM-517](https://helsinkisolutionoffice.atlassian.net/browse/YM-517)
[YM-517]: https://helsinkisolutionoffice.atlassian.net/browse/YM-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Upgrade to node14 YM-517

- CHANGELOG.md
[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
> chore: refactor changelog
