City-of-Helsinki/youth-membership-admin-ui

src/pages/youthProfiles/api/YouthApi.ts, src/pages/youthProfiles/create/inputs/BirthDateInput.tsx
Added `e.persist()` to make sure `e.target.id` is still available when passing data to `onChange` function. Birthdate is also formatted before sending data to backend.
=> OM - 557 | Fix birthDate input

src/pages/youthProfiles/list/YouthList.module.css, src/pages/youthProfiles/list/YouthList.tsx
Moved search results text to be before datagrid. It's original position was inside `profiles.length > 0` check which resulted text not showing with 0 results.
=> OM - 559 | Search with no results

src/pages/youthProfiles/helpers/__tests__/youthFormValidator.test.ts, src/pages/youthProfiles/helpers/youthFormValidator.ts
When the user submits the form for creating or editing a youth profile,
the form appears to do nothing.
This was caused by:
1) The validation function always adding the 'primaryAddress' field
into the error object. If primary address was valid, the value of
this field was an empty object. Otherwise it contained information
about sub-field errors.
2) The form submit handler ensuring that the callback function would
not be called if the the error object had any content (had any
keys).
This meant that the form would always be in an error state, but in such
a way that the user was not able to detect it, or recover from it.
I fixed this bug by creating an extra conditional that checks if the
'primaryAddress' field has any errors, and only then adds an object for
it in the errors object.
=> YM-81 | Fix save button

src/App.tsx, src/auth/api/api.ts, src/auth/api/queries.ts, src/auth/authProvider.ts, src/auth/components/checkPermissions/CheckPermissions.tsx, src/auth/components/notAuthorized/NotAuthorized.tsx, src/auth/components/oidcCallback/OidcCallback.tsx, src/auth/components/protectedResource/ProtectedResource.tsx, src/auth/components/protectedRoute/ProtectedRoute.tsx, src/auth/useAuthorized.ts, src/graphql/dataProvider.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/dashboard/Dashboard.tsx, src/routes.tsx
Previously all users were able to access the admin UI. If they did not
have correct priviledges, they weren't able to fetch data.
After this change those users are no longer able to see the admin UI.
As authentication does not provide information about user
authorization, we are using a protected query to find out if the user
is authorized to use the admin.
=> YM-61 | Stop non-admin users from accessing admin UI

src/auth/api/queries.ts
Previously the permission query fetched a lot of profiles. Here we limit the set into 1.
=> YM-61 | Optimize permission query

CONTRIBUTING.md
Updated the contribution guidelines so that it contains our developer email group.
=> YM-309 | Add youth membership email group to contributing.md

src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/youthProfiles/constants/youthProfileConstants.ts
I changed the max age of the service to 29 via configuration and changed the corresponding validation error messages.
=> YM-313 | Change registration max age limit to 29

.gitlab-ci.yml, package.json
OIDC_CLIENT_ID was changed earlier to use the public Youth membership UI's
id. I fixed this so that it's now correct.
Bumped the package version to 1.0.1.
=> YM-323 | Fix OIDC_CLIENT_ID in production CI configuration

src/auth/api/queries.ts, src/graphql/generatedTypes.ts, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/pages/youthProfiles/edit/EditYouthProfile.tsx, src/pages/youthProfiles/form/YouthProfileArrayField.tsx, src/pages/youthProfiles/form/YouthProfileForm.module.css, src/pages/youthProfiles/form/YouthProfileForm.tsx, src/pages/youthProfiles/form/youthProfileArrayField.module.css, src/pages/youthProfiles/helpers/__tests__/prepareArrayFieldChanges.test.ts, src/pages/youthProfiles/helpers/__tests__/utils.test.ts, src/pages/youthProfiles/helpers/__tests__/youthFormValidator.test.ts, src/pages/youthProfiles/helpers/getAdditionalContactPersons.ts, src/pages/youthProfiles/helpers/prepareArrayFieldChanges.ts, src/pages/youthProfiles/helpers/youthFormValidator.ts, src/pages/youthProfiles/helpers/youthProfileMutationVariables.ts, src/pages/youthProfiles/query/YouthProfileQueries.ts, src/pages/youthProfiles/types/youthProfileTypes.ts
Youth admins can control additional contact persons when adding a new youth, or when editing one. Validation, prefilling etc. should work.
I've tested this with a few unit tests for the validator because it's so complex. I also added a simple smoke test for the `prepareArrayField` because it may be hard tounderstand.
I didn't add more tests because they should likely be implemented through `e2e`.
=> YM-21, YM-13 | Allow youth admins to control additional contact persons

src/pages/youthProfiles/form/YouthProfileForm.tsx, src/pages/youthProfiles/helpers/__tests__/youthFormValidator.test.ts, src/pages/youthProfiles/helpers/youthFormValidator.ts, src/pages/youthProfiles/show/YouthDetails.tsx
Previously a valid item in an array would be represented by nothing. Only invalid items would cause new items to be added into an array. This meant that invalid items' errors would be matched incorrectly in the view layer if that item was preceded by valid items.
=> YM-21 | Fix array validation

src/pages/dashboard/Dashboard.tsx, src/pages/youthProfiles/api/YouthApi.ts, src/pages/youthProfiles/list/YouthList.tsx
The new version of `react-admin` dropped support for the way we were using the library. Although the version change was minor, and should therefore have been backwards compatible, we used `react-admin` in a special way which `react-admin` didn't likely consider to be officially supported.
The fix here was to refactor the list view in a way where it's more in line with the `react-admin` ethos. This way we can retain the newer version that does not include library side bugs that caused errors in some of our views.
I have tested this view by hand, because the functionality here heavily depends on the API. `e2e` integration is in the pipeline as its own separate task. I've also tested (by hand) the other views with happy paths:
- Profile "show" page
- Profile edit page
- Profile create page
=> YM-288 | Fix list view

src/pages/youthProfiles/helpers/__tests__/youthFormValidator.test.ts, src/pages/youthProfiles/helpers/youthFormValidator.ts
This change should fix the last bug described [here](https://helsinkisolutionoffice.atlassian.net/browse/YM-21). Entering a value and then removing would leave empty string as a value and it would pass previous checks inside `validateObject` function. 
Additional guardians email field would always throw `validation.email`.  I added this same logic to first guardian, so error messages are aligned.
=> YM-21 | Fix multiple guardian validation.

src/pages/youthProfiles/form/YouthProfileForm.module.css, src/pages/youthProfiles/form/YouthProfileForm.tsx
Move `FormGroupDescription` outside of `rowContainer` wrapper. With larger screens `flex:wrap` would but additional approver fields next to `FormGroupDescription` text. I also added little extra margin to top and bottom to isolate the text little better.
=> YM-348 | Fix layout breaking

browser-tests/pages/youthInformationSelector.ts, browser-tests/pages/youthListSelector.ts, browser-tests/youthListView.ts
Improved search list `e2e` tests.
1) Search for profile that has a unique name
2) Test that search results appear
3) Test navigation to youth profile
4) Navigate back to search list, and test that search terms still exists and search is executed again 
All search list functionalities are now covered.
[YM-382](https://helsinkisolutionoffice.atlassian.net/browse/YM-382)
`yarn browser-test` -> all tests pass.
1) Add values to `.env ` file (if you don't have these you can contact me):
- `REACT_APP_TESTING_USERNAME`
- `REACT_APP_TESTING_USERNAME_NO_ACCESS`
- `REACT_APP_TESTING_PASSWORD`
2) Login to [profile-admin](https://profiili-api.test.kuva.hel.ninja/admin/) and make sure "Ulla User" has no profile
3) Start local application `yarn start`
4) Run `yarn browser-test`
5) Delete the created …
=> YM-382 | Improve search list e2e tests.

browser-tests/pages/registrationFormSelector.ts, browser-tests/pages/youthInformationSelector.ts, browser-tests/util/registrationFormFillers.ts, browser-tests/youthProfileInformationView.ts
More `e2e` - tests. After these all main functionalities are covered. 
I made a little risky decision with `youthProfileInformationView`, it enter's one of the youth's profiles using existing ID (ID is hard coded...). Testing this functionality is a must, it simulates behaviour when staff member reads youth's QR code. 
I left a TODO comment to figure it out at some point.
Adds more test coverage. I found one bug while writing these tests. It's documented [here](https://helsinkisolutionoffice.atlassian.net/browse/YM-408)
[YM-383](https://helsinkisolutionoffice.atlassian.net/browse/YM-383)
[YM-384](https://helsinkisolutionoffice.atlassian.net/browse/YM-384)
`yarn browser-test` -> all tests pass.
1) Add values to `.env ` file (if you don't have these you can contact me):
- …
=> YM-383, YM-384 |  E2e tests for editing profile information.

.gitignore, .travis.yml, README.md, browser-tests/pages/loginSelector.ts, browser-tests/pages/registrationFormSelector.ts, package.json
These changes configure browser tests to run on Travis cron jobs.
I had to modify one selector, because it didn't work for a production version of the build where `makeStyles` classes are shortened.
I also configured the environment and cron jobs in Travis against `develop`.
[YM-340](https://helsinkisolutionoffice.atlassian.net/browse/YM-340)
I've ran browser tests locally against the current staging version with both commands.
I configured cron to run against this branch and checked that it passed.
No real manual steps, but you could check out the cron test ran against this branch:
* https://travis-ci.com/github/City-of-Helsinki/youth-membership-admin-ui/jobs/428566146
=> YM-340 | Run browser tests in Travis

README.md, browser-tests/youthProfileInformationView.ts
A missing slash caused the the domain name to be incorrectly formatted.
You can check that browser tests now pass here: https://github.com/City-of-Helsinki/youth-membership-admin-ui/runs/1457649521?check_suite_focus=true
I ran browser tests manually against this branch, meaning that I used the workflow configuration from this branch.
I also updated the readme.
=> Chore | Fix browser test by adding missing slash

.github/workflows/production.yml, .gitlab-ci.yml, CHANGELOG.md
Uses the public API for Jassari. The non-public endpoint may not be enabled for all users.
=> Chore | Use public Jassari API

.env.example, .github/workflows/staging.yml, src/auth/__tests__/__snapshots__/authService.test.js.snap
Currently the backend uses Kuva's Tunnistamo and this application uses Kanlia's Tunnistamo. It means that the token we receive when authenticating with Kanslia's Tunnistamo, will not be consider valid by Kuvaäs Tunnistamo.
=> FIX | Use the same tunnistamo as the backend does

.github/workflows/production.yml, .github/workflows/review.yml, .github/workflows/staging.yml
The configurations had inherited the string concatenation pattern from the GitLab config, which does not work in GitHub actions, leading to a misconfigured Tunnistamo integration.
=> FIX | Fix CD configs for all environments 

.github/workflows/production.yml
Reverts the production config to use older helsinki profile backend. These variables names were a bit different than I remembered, but I think I changed the correct ones.
=> Fix production build

.github/workflows/production.yml, CHANGELOG.md
Updated documentation relating to releases.
Reverted earlier changes where production workflow's url's were pointed to helsinki profiles backend.
=> Chore | Update changelog and revert earlier backend url changes.

CHANGELOG.md, src/pages/youthProfiles/helpers/__tests__/youthProfileMutationVariables.test.js, src/pages/youthProfiles/helpers/youthProfileMutationVariables.ts
Fix behaviour where the user could not set a non-required field as empty (for instance the schoolClass field).
This was because the values sent to the server were based on the form values provided by react-admin, and react-final-form within it. In these values empty values were defined as undefined, which meant that they were omitted entirely from the object sent to the server.
[YM-408](https://helsinkisolutionoffice.atlassian.net/browse/YM-408)
I added a unit test that checks that empty values receive an empty default value.
=> YM-408 | Fix non-required fields being unclearable

.env.example, CHANGELOG.md, src/auth/__tests__/__snapshots__/authService.test.js.snap, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Changes the label of the field profileLanguage to "Preferred service language".
Also fixes the default environment. It was missing an ending slash which caused the Tunnistamo integration to fail.
[YM-502](https://helsinkisolutionoffice.atlassian.net/browse/YM-502)
I've tested the change by hand.
=> YM-502 | Change label Profile language to Preferred service language

.github/workflows/browser-test.yml, browser-tests/pages/registrationFormSelector.ts, browser-tests/pages/youthInformationSelector.ts, browser-tests/registrationView.ts, browser-tests/util/login.ts, browser-tests/youthProfileInformationView.ts
Browser tests have been working poorly in the past few months. I added more wait time after login which will hopefully help with the issues.
The recent changes to the language at home field also broke the test suite. Testcafe was also provided with an environment url that contained an ending slash, which broke redirection logic in some tests. I adjusted the URL creation logic so that the same url is returned regardless of an ending slash.
Test now pass here: https://github.com/City-of-Helsinki/youth-membership-admin-ui/actions/runs/708616409
=> Fix browser tests

src/auth/components/login/Login.tsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/index.css
Note: in the react-admin its easier to add notification inside the login card, as its using the default Login component as "page" component.
[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
=> fix: service not available
